[package]
name = "rb_term"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.28", default-features = false, features = ["term", "process", "fs"] }
eframe = "0.27"
tracing = "0.1"
tracing-subscriber = "0.3"

